# From: https://docs.travis-ci.com/user/languages/php/
# "PHP 5.6(.x) - 7.0(.x) support is available on Precise, Trusty and Xenial only"
dist: trusty

# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 7.x version
  - 7.0

matrix:
  include:
  - php: 7.2.6
    env: WP_VERSION=latest
  - php: 7.1.18
    env: WP_VERSION=latest
  - php: 7.0.32
    env: WP_VERSION=latest
  - php: 5.6.37
    env: WP_VERSION=4.4
  - php: 5.6.37
    env: WP_VERSION=latest

before_script:
  - php -r "printf('PHP %s', phpversion());"
  - ./tests/before_script.sh
  
# optionally specify a list of environments, for example to test different RDBMS
#env:
#  - DB=mysql
#  - DB=pgsql

# optionally set up exclusions and allowed failures in the matrix
#matrix:
#  exclude:
#    - php: hhvm
#      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
#  allow_failures:
#    - php: 7.0
#    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
#before_script:
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
#script: phpunit --configuration phpunit_$DB.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
#notifications:
#  email: "irc.freenode.org#yourfavouriteroomfortravis"
